# Generated by Django 6.0.4 on 2026-05-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Istirahat/Sholat', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Hari apa istirahat ini berlaku')),
                ('kapster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('service_name', models.CharField(blank=True, help_text='Snapshot service name', max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('proses', 'Diproses'), ('selesai', 'Selesai'), ('tertunda', 'Tertunda (Delayed)'), ('batal', 'Batal')], default='menunggu', max_length=10)),
                ('scheduled_time', models.DateTimeField(help_text='Jadwal asli saat booking')),
                ('estimated_start', models.DateTimeField(help_text='Waktu mulai yang dinamis (Dynamic EST)')),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('is_walk_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kapster', models.ForeignKey(limit_choices_to={'role': 'kapster'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='services.service')),
            ],
            options={
                'ordering': ['estimated_start'],
                'constraints': [models.UniqueConstraint(fields=('kapster', 'scheduled_time'), name='unique_kapster_reservation_time')],
            },
        ),
    ]
