# Generated by Django 6.0.4 on 2026-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('kapster', 'Kapster'), ('pelanggan', 'Pelanggan')], default='pelanggan', max_length=10),
        ),
    ]
